# Generated by Django 5.1.3 on 2024-12-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='face_encoding',
        ),
        migrations.AddField(
            model_name='customuser',
            name='down',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='left',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='right',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='up',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/<django.db.models.fields.CharField>'),
        ),
    ]
